[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/snippets/*"
  to = "/blog/:splat"

[[redirects]]
  from = "https://uridge-com.netlify.app/"
  to = "https://www.uridge.com/"
  force = true

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/ruridge/"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/roburidge"

[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/roburidge/"