[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/snippets/*"
  to = "/blog/:splat"

[[redirects]]
  from = "https://uridge-com.netlify.app/"
  to = "https://www.uridge.com/"
  force = true